name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ jruby-9.1.17.0, jruby-9.2.20.1, jruby-9.3.2.0, 2.0.0-p648, 2.1.9, 2.2.10, 2.4.10, 2.5.9, 2.6.9, 2.7.5, 3.0.3, 3.1.0 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: Run tests
        run: bundle exec rspec -t ~https -t ~unresolved
